### ISSUE TITLE
Exception on running firehose sample

### ISSUE THREAD

**Issue by TimBurga** [drasticactions/FishyFlip#10]
Unfortunately it looks like it may be a race condition in the 3rd party library

```
System.ArgumentException: The IPFS codec name 'codec-1' is already defined.
   at Ipfs.Registry.Codec.Register(String name, Int32 code)
   at Ipfs.MultiCodec.ReadMultiCodec(Stream stream)
   at Ipfs.Cid.Read(Byte[] buffer)
   at FishyFlip.Tools.Cbor.CborExtensions.ToCid(CBORObject obj)
```

**Comment by drasticactions** [comment]
It's known, you can ignore it. It doesn't break the underlying code.

**Comment by drasticactions** [comment]
For now, we can handle it by outputting the error to the logger so the rest of the object can come through, and you can still act on the error by passing in an `ILogger` to the underlying Firehose class. 

https://github.com/drasticactions/FishyFlip/commit/1c280a3736fc4091d1cc909d2d5a60647d54059c

Since `Cid` is nullable, your code should already be handling cases where it could be null. I would need to look further if there's something I'm missing by not registering the types in advance, or if it is a race condition in the Ipfs library.

**Comment by drasticactions** [comment]
This should be fixed with https://github.com/drasticactions/FishyFlip/pull/167 and the bump to the newest Peter.CBOR library in the last few releases. If it still happens in this release or up, feel free to reopen it.
