### ISSUE TITLE
Cannot subscribe to firehose

### ISSUE THREAD

**Issue by Isolyth** [drasticactions/FishyFlip#82]
Hi! I am trying to subscribe to the firehose using the latest version of fishyflip and the included firehose sample, but if I try to subscribe to anything other than my own PDS or another small PDS, I get 

`FishyFlipDebug: Error: This object's value is out of range

System.OverflowException: This object's value is out of range
   at PeterO.Cbor.CBORInteger.AsInt32(Object obj, Int32 minValue, Int32 maxValue)
   at PeterO.Cbor.CBORObject.AsInt32(Int32 minValue, Int32 maxValue)
   at PeterO.Cbor.CBORObject.AsInt32()
   at FishyFlip.Models.FrameCommit..ctor(CBORObject obj, ILogger logger) in /_/src/FishyFlip/Models/FrameCommit.cs:line 20
   at FishyFlip.ATWebSocketProtocol.HandleMessage(Byte[] byteArray) in /_/src/FishyFlip/ATWebSocketProtocol.cs:line 209
   at FishyFlip.ATWebSocketProtocol.<>c__DisplayClass30_0.<ReceiveMessages>b__0() in /_/src/FishyFlip/ATWebSocketProtocol.cs:line 304
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at FishyFlip.Tools.TaskUtilities.FireAndForgetSafeAsync(Task task, ILogger handler) in /_/src/FishyFlip/Tools/TaskUtilities.cs:line 23`

**Comment by drasticactions** [comment]
That was a legit error, `Seq` was higher than `Int32`. The lexicon puts it as a `number` (https://github.com/bluesky-social/atproto/blob/9e18ab6a35f47e0a9cee76221bfa0817c8a624a1/lexicons/com/atproto/sync/subscribeRepos.json#L57-L60), and when I first wrote it, it would have made sense to keep it as an int. Guess I couldn't have assumed ATProtocol would have lasted this far ;-).

Making it a `long` fixes it. You can access the build from https://www.nuget.org/packages/FishyFlip/2.2.0-alpha.2, and I'll backport this to 2.1.
