### ISSUE TITLE
AuthenticateWithPasswordAsync failes with System.FormatException: Input string was not in a correct format. Failure to parse near offset 12. Expected an ASCII digit.

### ISSUE THREAD

**Issue by raymondandreassen** [drasticactions/FishyFlip#86]
AuthenticateWithPasswordAsync failes. I did a final test before I posted this issue [using your code](https://github.com/drasticactions/FishyFlip/blob/develop/samples/PasswordAuth/Program.cs) to produce the error message below. 

In short: 
```
var session = await protocol.AuthenticateWithPasswordAsync(identifier, password, cancellationToken);
```
Failes with: 
```
System.FormatException: Input string was not in a correct format. Failure to parse near offset 12. Expected an ASCII digit.
   at System.Text.CompositeFormat.Parse(String format)
   at Microsoft.Extensions.Logging.LogValuesFormatter..ctor(String format)
   at Microsoft.Extensions.Logging.FormattedLogValues.<>c.<.ctor>b__9_0(String f)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Microsoft.Extensions.Logging.FormattedLogValues..ctor(String format, Object[] values)
   at Microsoft.Extensions.Logging.LoggerExtensions.Log(ILogger logger, LogLevel logLevel, EventId eventId, Exception exception, String message, Object[] args)
   at Microsoft.Extensions.Logging.LoggerExtensions.Log(ILogger logger, LogLevel logLevel, String message, Object[] args)
   at Microsoft.Extensions.Logging.LoggerExtensions.LogError(ILogger logger, String message, Object[] args)
   at FishyFlip.PasswordSessionManager.<>c__DisplayClass25_0.<CreateSessionAsync>b__1(ATError e) in /_/src/FishyFlip/PasswordSessionManager.cs:line 139
   at FishyFlip.Tools.Multiple`2.Switch(Action`1 f0, Action`1 f1) in /_/src/FishyFlip/Tools/Multiple.cs:line 129
   at FishyFlip.PasswordSessionManager.CreateSessionAsync(String identifier, String password, CancellationToken cancellationToken) in /_/src/FishyFlip/PasswordSessionManager.cs:line 108
   at FishyFlip.ATProtocol.AuthenticateWithPasswordAsync(String identifier, String password, CancellationToken cancellationToken) in /_/src/FishyFlip/ATProtocol.cs:line 177
   at AppCommands.AuthenticateAsync(String identifier, String password, CancellationToken cancellationToken) in C:\Data\CodePrivate\BSky\OAuth2LoginTest\Program.cs:line 37
   at ConsoleAppFramework.ConsoleApp.ConsoleAppBuilder.RunCommand0(String[] rawArgs, ReadOnlySpan`1 args) in C:\Data\CodePrivate\BSky\OAuth2LoginTest\obj\Debug\net8.0\ConsoleAppFramework\ConsoleAppFramework.ConsoleAppGenerator\ConsoleApp.Builder.g.cs:line 105
```

**Comment by drasticactions** [comment]
@raymondandreassen Yeah, it was failing in the logging when processing `ATError` as an object. As it's already returned in the error message itself, that should be enough to understand what happened so I removed it.

This also means that you most likely have another issue (My guess would be `401` Unauthorized, I.E Wrong username/password). If you're hitting something else it should be outputted now by the logger. If you're still having issues with it, feel free to file another issue.

https://www.nuget.org/packages/FishyFlip/2.2.0-alpha.4

Your fix should be available in this.
